### ISSUE TITLE
Deployment Setup

### ISSUE THREAD

**Issue by nazi254** [PLOS/ambraproject#14]
I am trying to deploy this system on Microsoft Azure with the Ubuntu VM,after successfully clowning and deploying the app to the portal,It cant load the web page and I have the error as seen on this url http://ambrastack.azurewebsites.net. I used Kudu to deploy the .war files too. Could anyone help on how the system is being installed as the documentation provided has a lot of instructions but no detail as to which or what should be done first.

Regards

**Comment by sjtower** [comment]
Hi there. Clicking on the link you provided does not show an error. Would you mind pasting the error here?

**Comment by nazi254** [comment]
Ok on click the link,I expected to see the Ambra web app on the URL after
having pushed the files from Github. So am lacking the content. How do get
the content and how do we push it?

Thats my problem. Have you tried hosting it in the cloud? If yes which one
and how did you go about it.

Regards

**Comment by sjtower** [comment]
I'm afraid that we have never tried hosting the stack in the cloud so we cannot offer much support.

@anilop will continue assisting you via email.
