### ISSUE TITLE
URL for Journal Setup Page and Front End 

### ISSUE THREAD

**Issue by StVicious** [PLOS/ambraproject#16]
Hi, 

I am following the step-by-step instructions (via https://plos.github.io/ambraproject/Quickstart-Guide.html) to install Ambra. 

A quick question: Once I complete the installation, what will be the URLs to launch the Ambra Journal setup page (for editor to set up the journal) and front end page (for general visitors to view the Journal)? 

Thanks!

**Comment by sjtower** [comment]
Hi StVicious, thanks for trying out our software.

Ambra is a standard Java web application, so the front end URL would be defined in your server configuration. We use Apache and define our front-end URLs there. 

The Ambra project does not come with any admin or setup pages. You'll have to manually alter the database or write your own tools to interface with the Ambra API endpoints.

We have written our own admin interface but unfortunately haven't made it open-source yet. 

Please let us know if you have any other questions.

**Comment by StVicious** [comment]
Thank you very much for your great help!
