### ISSUE TITLE
Ambra Installation Error message - database related

### ISSUE THREAD

**Issue by StVicious** [PLOS/ambraproject#17]
Hi, 

I am installing Ambra, and am struggling with the following error message. It appears to be related to database connection. 

contentrepo_1   | ERROR 2003 (HY000): Can't connect to MySQL server on 'repodb' (111 "Connection refused")

rhino_1         | ERROR 2003 (HY000): Can't connect to MySQL server on 'ambradb_demo' (111 "Connection refused")

rhino_1         | ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails (`ambra`.`articleIngestion`, CONSTRAINT `fk_articleIngestion_2` FOREIGN KEY (`journalId`) REFERENCES `journal` (`journalId`) ON DELETE NO ACTION ON UPDATE NO ACTION)

Can you please provide some insight? Really appreciate your help!

**Comment by jonocodes** [comment]
It seems like there was an issue with the database migrations when rhino was run in example mode. I have fixed it now so you should not run into this problem.

Do this to clear your setup out:

./nv stack ambra_minimal rm -f
docker rmi plos/rhino:2.2.2

Then when you run again, it will pull the fixed image. You will have to reingest your articles.
